//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v8.18.5
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder.Embedded;

namespace Umbraco.Web.PublishedModels
{
	/// <summary>Country Item</summary>
	[PublishedModel("countryItem")]
	public partial class CountryItem : PublishedContentModel, IPageBasics, IPageVisibility, ISeosmo, ITags
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		public new const string ModelTypeAlias = "countryItem";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<CountryItem, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public CountryItem(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// What we do there
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("backgroundWhat")]
		public virtual global::System.Web.IHtmlString BackgroundWhat => this.Value<global::System.Web.IHtmlString>("backgroundWhat");

		///<summary>
		/// Why we are there
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("backgroundWhy")]
		public virtual global::System.Web.IHtmlString BackgroundWhy => this.Value<global::System.Web.IHtmlString>("backgroundWhy");

		///<summary>
		/// Chart Embed: Paste your responsive embed code here
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("chartEmbed")]
		public virtual string ChartEmbed => this.Value<string>("chartEmbed");

		///<summary>
		/// Chart Source Link: Link to your data source
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("chartSourceLink")]
		public virtual string ChartSourceLink => this.Value<string>("chartSourceLink");

		///<summary>
		/// Chart Source Name: Name of your data source
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("chartSourceName")]
		public virtual string ChartSourceName => this.Value<string>("chartSourceName");

		///<summary>
		/// Chart Title: Descriptive title for the chart
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("chartTitle")]
		public virtual string ChartTitle => this.Value<string>("chartTitle");

		///<summary>
		/// Contacts: Add country specific contacts here
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("contacts")]
		public virtual global::System.Collections.Generic.IEnumerable<global::Umbraco.Core.Models.PublishedContent.IPublishedContent> Contacts => this.Value<global::System.Collections.Generic.IEnumerable<global::Umbraco.Core.Models.PublishedContent.IPublishedContent>>("contacts");

		///<summary>
		/// Coordinates Latitude: Right click on Google Maps to fetch it
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("coordinatesLatitude")]
		public virtual string CoordinatesLatitude => this.Value<string>("coordinatesLatitude");

		///<summary>
		/// Coordinates Longitude: Right click on Google Maps to fetch it
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("coordinatesLongitude")]
		public virtual string CoordinatesLongitude => this.Value<string>("coordinatesLongitude");

		///<summary>
		/// Current Situation: Keep it short. Update often.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("currentSituation")]
		public virtual global::System.Web.IHtmlString CurrentSituation => this.Value<global::System.Web.IHtmlString>("currentSituation");

		///<summary>
		/// External Links
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("links")]
		public virtual global::System.Collections.Generic.IEnumerable<global::Umbraco.Web.PublishedModels.CountryLink> Links => this.Value<global::System.Collections.Generic.IEnumerable<global::Umbraco.Web.PublishedModels.CountryLink>>("links");

		///<summary>
		/// Partners: Add country specific partners here
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("partners")]
		public virtual global::System.Collections.Generic.IEnumerable<global::Umbraco.Core.Models.PublishedContent.IPublishedContent> Partners => this.Value<global::System.Collections.Generic.IEnumerable<global::Umbraco.Core.Models.PublishedContent.IPublishedContent>>("partners");

		///<summary>
		/// Camp Management: Switch on if sector is active in this country
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("sectorCamps")]
		public virtual bool SectorCamps => this.Value<bool>("sectorCamps");

		///<summary>
		/// Disarmament and Peacebuilding: Switch on if sector is active in this country
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("sectorDemining")]
		public virtual bool SectorDemining => this.Value<bool>("sectorDemining");

		///<summary>
		/// Protection: Switch on if sector is active in this country
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("sectorProtection")]
		public virtual bool SectorProtection => this.Value<bool>("sectorProtection");

		///<summary>
		/// Economic Recovery: Switch on if sector is active in this country
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("sectorRecovery")]
		public virtual bool SectorRecovery => this.Value<bool>("sectorRecovery");

		///<summary>
		/// Shelter and Settlement: Switch on if sector is active in this country
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("sectorShelter")]
		public virtual bool SectorShelter => this.Value<bool>("sectorShelter");

		///<summary>
		/// Description
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("description")]
		public virtual string Description => global::Umbraco.Web.PublishedModels.PageBasics.GetDescription(this);

		///<summary>
		/// Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("image")]
		public virtual global::Umbraco.Core.Models.MediaWithCrops Image => global::Umbraco.Web.PublishedModels.PageBasics.GetImage(this);

		///<summary>
		/// Image Credits
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("imageCredits")]
		public virtual string ImageCredits => global::Umbraco.Web.PublishedModels.PageBasics.GetImageCredits(this);

		///<summary>
		/// Image Visible
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("imageVisible")]
		public virtual bool ImageVisible => global::Umbraco.Web.PublishedModels.PageBasics.GetImageVisible(this);

		///<summary>
		/// Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("title")]
		public virtual string Title => global::Umbraco.Web.PublishedModels.PageBasics.GetTitle(this);

		///<summary>
		/// Hide from robots
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("hideFromRobots")]
		public virtual bool HideFromRobots => global::Umbraco.Web.PublishedModels.PageVisibility.GetHideFromRobots(this);

		///<summary>
		/// Hide from sitemap
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("hideFromSitemap")]
		public virtual bool HideFromSitemap => global::Umbraco.Web.PublishedModels.PageVisibility.GetHideFromSitemap(this);

		///<summary>
		/// Hide from navigation
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("umbracoNaviHide")]
		public virtual bool UmbracoNaviHide => global::Umbraco.Web.PublishedModels.PageVisibility.GetUmbracoNaviHide(this);

		///<summary>
		/// Short URL: 'abc' creates 'drc.ngo/abc'
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("umbracoUrlAlias")]
		public virtual string UmbracoUrlAlias => global::Umbraco.Web.PublishedModels.PageVisibility.GetUmbracoUrlAlias(this);

		///<summary>
		/// SEO Description: For search engines (e.g. Google)
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("seoDescription")]
		public virtual string SeoDescription => global::Umbraco.Web.PublishedModels.Seosmo.GetSeoDescription(this);

		///<summary>
		/// SEO Title: For search engines (e.g. Google)
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("seoTitle")]
		public virtual string SeoTitle => global::Umbraco.Web.PublishedModels.Seosmo.GetSeoTitle(this);

		///<summary>
		/// SMO Description: For social media (e.g. Facebook)
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("smoDescription")]
		public virtual string SmoDescription => global::Umbraco.Web.PublishedModels.Seosmo.GetSmoDescription(this);

		///<summary>
		/// SMO Title: For social media (e.g. Facebook)
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("smoTitle")]
		public virtual string SmoTitle => global::Umbraco.Web.PublishedModels.Seosmo.GetSmoTitle(this);

		///<summary>
		/// Location Tags
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("locationTags")]
		public virtual global::System.Collections.Generic.IEnumerable<string> LocationTags => global::Umbraco.Web.PublishedModels.Tags.GetLocationTags(this);

		///<summary>
		/// Tags Visible
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("tagsVisible")]
		public virtual bool TagsVisible => global::Umbraco.Web.PublishedModels.Tags.GetTagsVisible(this);

		///<summary>
		/// Topic Tags
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("topicTags")]
		public virtual global::System.Collections.Generic.IEnumerable<string> TopicTags => global::Umbraco.Web.PublishedModels.Tags.GetTopicTags(this);
	}
}
