//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v8.18.5
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder.Embedded;

namespace Umbraco.Web.PublishedModels
{
	/// <summary>Event Item</summary>
	[PublishedModel("eventItem")]
	public partial class EventItem : PublishedContentModel, IPageBasics, IPageVisibility, ISeosmo, ITags
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		public new const string ModelTypeAlias = "eventItem";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<EventItem, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public EventItem(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Agenda
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("agenda")]
		public virtual global::System.Collections.Generic.IEnumerable<global::Umbraco.Core.Models.PublishedContent.IPublishedElement> Agenda => this.Value<global::System.Collections.Generic.IEnumerable<global::Umbraco.Core.Models.PublishedContent.IPublishedElement>>("agenda");

		///<summary>
		/// Currency
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("currency")]
		public virtual string Currency => this.Value<string>("currency");

		///<summary>
		/// Event End Date
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("eventEndDate")]
		public virtual global::System.DateTime EventEndDate => this.Value<global::System.DateTime>("eventEndDate");

		///<summary>
		/// Event Link
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("eventLink")]
		public virtual string EventLink => this.Value<string>("eventLink");

		///<summary>
		/// Event Start Date
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("eventStartDate")]
		public virtual global::System.DateTime EventStartDate => this.Value<global::System.DateTime>("eventStartDate");

		///<summary>
		/// Participate Online
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("locationOnline")]
		public virtual bool LocationOnline => this.Value<bool>("locationOnline");

		///<summary>
		/// Price | Discounted
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("priceDiscounted")]
		public virtual int PriceDiscounted => this.Value<int>("priceDiscounted");

		///<summary>
		/// Price | Standard
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("priceStandard")]
		public virtual int PriceStandard => this.Value<int>("priceStandard");

		///<summary>
		/// Registration Deadline | Discounted
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("registrationDeadlineDiscounted")]
		public virtual global::System.DateTime RegistrationDeadlineDiscounted => this.Value<global::System.DateTime>("registrationDeadlineDiscounted");

		///<summary>
		/// Registration Deadline | Standard
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("registrationDeadlineStandard")]
		public virtual global::System.DateTime RegistrationDeadlineStandard => this.Value<global::System.DateTime>("registrationDeadlineStandard");

		///<summary>
		/// Registration Link
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("registrationLink")]
		public virtual string RegistrationLink => this.Value<string>("registrationLink");

		///<summary>
		/// Speakers
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("speakers")]
		public virtual global::System.Collections.Generic.IEnumerable<global::Umbraco.Web.PublishedModels.EventSpeaker> Speakers => this.Value<global::System.Collections.Generic.IEnumerable<global::Umbraco.Web.PublishedModels.EventSpeaker>>("speakers");

		///<summary>
		/// Venue Address
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("venueAddress")]
		public virtual string VenueAddress => this.Value<string>("venueAddress");

		///<summary>
		/// Venue City
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("venueCity")]
		public virtual string VenueCity => this.Value<string>("venueCity");

		///<summary>
		/// Venue Country
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("venueCountry")]
		public virtual string VenueCountry => this.Value<string>("venueCountry");

		///<summary>
		/// Venue Name
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("venueName")]
		public virtual string VenueName => this.Value<string>("venueName");

		///<summary>
		/// Venue Zipcode
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("venueZipcode")]
		public virtual string VenueZipcode => this.Value<string>("venueZipcode");

		///<summary>
		/// Description
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("description")]
		public virtual string Description => global::Umbraco.Web.PublishedModels.PageBasics.GetDescription(this);

		///<summary>
		/// Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("image")]
		public virtual global::Umbraco.Core.Models.MediaWithCrops Image => global::Umbraco.Web.PublishedModels.PageBasics.GetImage(this);

		///<summary>
		/// Image Credits
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("imageCredits")]
		public virtual string ImageCredits => global::Umbraco.Web.PublishedModels.PageBasics.GetImageCredits(this);

		///<summary>
		/// Image Visible
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("imageVisible")]
		public virtual bool ImageVisible => global::Umbraco.Web.PublishedModels.PageBasics.GetImageVisible(this);

		///<summary>
		/// Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("title")]
		public virtual string Title => global::Umbraco.Web.PublishedModels.PageBasics.GetTitle(this);

		///<summary>
		/// Hide from robots
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("hideFromRobots")]
		public virtual bool HideFromRobots => global::Umbraco.Web.PublishedModels.PageVisibility.GetHideFromRobots(this);

		///<summary>
		/// Hide from sitemap
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("hideFromSitemap")]
		public virtual bool HideFromSitemap => global::Umbraco.Web.PublishedModels.PageVisibility.GetHideFromSitemap(this);

		///<summary>
		/// Hide from navigation
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("umbracoNaviHide")]
		public virtual bool UmbracoNaviHide => global::Umbraco.Web.PublishedModels.PageVisibility.GetUmbracoNaviHide(this);

		///<summary>
		/// Short URL: 'abc' creates 'drc.ngo/abc'
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("umbracoUrlAlias")]
		public virtual string UmbracoUrlAlias => global::Umbraco.Web.PublishedModels.PageVisibility.GetUmbracoUrlAlias(this);

		///<summary>
		/// SEO Description: For search engines (e.g. Google)
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("seoDescription")]
		public virtual string SeoDescription => global::Umbraco.Web.PublishedModels.Seosmo.GetSeoDescription(this);

		///<summary>
		/// SEO Title: For search engines (e.g. Google)
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("seoTitle")]
		public virtual string SeoTitle => global::Umbraco.Web.PublishedModels.Seosmo.GetSeoTitle(this);

		///<summary>
		/// SMO Description: For social media (e.g. Facebook)
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("smoDescription")]
		public virtual string SmoDescription => global::Umbraco.Web.PublishedModels.Seosmo.GetSmoDescription(this);

		///<summary>
		/// SMO Title: For social media (e.g. Facebook)
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("smoTitle")]
		public virtual string SmoTitle => global::Umbraco.Web.PublishedModels.Seosmo.GetSmoTitle(this);

		///<summary>
		/// Location Tags
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("locationTags")]
		public virtual global::System.Collections.Generic.IEnumerable<string> LocationTags => global::Umbraco.Web.PublishedModels.Tags.GetLocationTags(this);

		///<summary>
		/// Tags Visible
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("tagsVisible")]
		public virtual bool TagsVisible => global::Umbraco.Web.PublishedModels.Tags.GetTagsVisible(this);

		///<summary>
		/// Topic Tags
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("topicTags")]
		public virtual global::System.Collections.Generic.IEnumerable<string> TopicTags => global::Umbraco.Web.PublishedModels.Tags.GetTopicTags(this);
	}
}
