//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v8.18.5
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder.Embedded;

namespace Umbraco.Web.PublishedModels
{
	/// <summary>News Item</summary>
	[PublishedModel("newsItem")]
	public partial class NewsItem : PublishedContentModel, IPageBasics, IPageVisibility, ISeosmo, ITags
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		public new const string ModelTypeAlias = "newsItem";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<NewsItem, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public NewsItem(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Basic Content
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("basicContent")]
		public virtual global::System.Web.IHtmlString BasicContent => this.Value<global::System.Web.IHtmlString>("basicContent");

		///<summary>
		/// Byline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("byline")]
		public virtual string Byline => this.Value<string>("byline");

		///<summary>
		/// Contact Email
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("contactEmail")]
		public virtual string ContactEmail => this.Value<string>("contactEmail");

		///<summary>
		/// Contact Name
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("contactName")]
		public virtual string ContactName => this.Value<string>("contactName");

		///<summary>
		/// Contact Office
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("contactOffice")]
		public virtual string ContactOffice => this.Value<string>("contactOffice");

		///<summary>
		/// Contact Position
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("contactPosition")]
		public virtual string ContactPosition => this.Value<string>("contactPosition");

		///<summary>
		/// Advanced Content
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("content")]
		public virtual global::System.Collections.Generic.IEnumerable<global::Umbraco.Core.Models.PublishedContent.IPublishedElement> Content => this.Value<global::System.Collections.Generic.IEnumerable<global::Umbraco.Core.Models.PublishedContent.IPublishedElement>>("content");

		///<summary>
		/// Phone Number
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("phoneNumber")]
		public virtual string PhoneNumber => this.Value<string>("phoneNumber");

		///<summary>
		/// Phone Prefix
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("phonePrefix")]
		public virtual string PhonePrefix => this.Value<string>("phonePrefix");

		///<summary>
		/// Timestamp
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("timestamp")]
		public virtual global::System.DateTime Timestamp => this.Value<global::System.DateTime>("timestamp");

		///<summary>
		/// Description
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("description")]
		public virtual string Description => global::Umbraco.Web.PublishedModels.PageBasics.GetDescription(this);

		///<summary>
		/// Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("image")]
		public virtual global::Umbraco.Core.Models.MediaWithCrops Image => global::Umbraco.Web.PublishedModels.PageBasics.GetImage(this);

		///<summary>
		/// Image Credits
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("imageCredits")]
		public virtual string ImageCredits => global::Umbraco.Web.PublishedModels.PageBasics.GetImageCredits(this);

		///<summary>
		/// Image Visible
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("imageVisible")]
		public virtual bool ImageVisible => global::Umbraco.Web.PublishedModels.PageBasics.GetImageVisible(this);

		///<summary>
		/// Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("title")]
		public virtual string Title => global::Umbraco.Web.PublishedModels.PageBasics.GetTitle(this);

		///<summary>
		/// Hide from robots
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("hideFromRobots")]
		public virtual bool HideFromRobots => global::Umbraco.Web.PublishedModels.PageVisibility.GetHideFromRobots(this);

		///<summary>
		/// Hide from sitemap
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("hideFromSitemap")]
		public virtual bool HideFromSitemap => global::Umbraco.Web.PublishedModels.PageVisibility.GetHideFromSitemap(this);

		///<summary>
		/// Hide from navigation
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("umbracoNaviHide")]
		public virtual bool UmbracoNaviHide => global::Umbraco.Web.PublishedModels.PageVisibility.GetUmbracoNaviHide(this);

		///<summary>
		/// Short URL: 'abc' creates 'drc.ngo/abc'
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("umbracoUrlAlias")]
		public virtual string UmbracoUrlAlias => global::Umbraco.Web.PublishedModels.PageVisibility.GetUmbracoUrlAlias(this);

		///<summary>
		/// SEO Description: For search engines (e.g. Google)
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("seoDescription")]
		public virtual string SeoDescription => global::Umbraco.Web.PublishedModels.Seosmo.GetSeoDescription(this);

		///<summary>
		/// SEO Title: For search engines (e.g. Google)
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("seoTitle")]
		public virtual string SeoTitle => global::Umbraco.Web.PublishedModels.Seosmo.GetSeoTitle(this);

		///<summary>
		/// SMO Description: For social media (e.g. Facebook)
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("smoDescription")]
		public virtual string SmoDescription => global::Umbraco.Web.PublishedModels.Seosmo.GetSmoDescription(this);

		///<summary>
		/// SMO Title: For social media (e.g. Facebook)
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("smoTitle")]
		public virtual string SmoTitle => global::Umbraco.Web.PublishedModels.Seosmo.GetSmoTitle(this);

		///<summary>
		/// Location Tags
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("locationTags")]
		public virtual global::System.Collections.Generic.IEnumerable<string> LocationTags => global::Umbraco.Web.PublishedModels.Tags.GetLocationTags(this);

		///<summary>
		/// Tags Visible
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("tagsVisible")]
		public virtual bool TagsVisible => global::Umbraco.Web.PublishedModels.Tags.GetTagsVisible(this);

		///<summary>
		/// Topic Tags
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("topicTags")]
		public virtual global::System.Collections.Generic.IEnumerable<string> TopicTags => global::Umbraco.Web.PublishedModels.Tags.GetTopicTags(this);
	}
}
